### ISSUE TITLE
Customizer Options

### ISSUE THREAD

**Issue by mauryaratan** [Codestag/thyself#1]
Here's the initial idea of Customizer theme options:

- [x] Theme Options
  - [x] Fonts
    - [x] Body font
    - [x] Header font
    - [x] Character Subset
  - [x] Front page
    - [x] Layouts
  - [x] Footer
    - [x] Number of widget areas
    - [x] Copyright text

Notes:
- Let's make use of [select2](https://select2.org/) here for long select and multi-selects.

**Comment by lushkant** [comment]
Done! 🥂
