### ISSUE TITLE
Missing right border on homepage

### ISSUE THREAD

**Issue by mauryaratan** [Codestag/thyself#13]
When homepage layout is set to Sidebar + Content, the sidebar doesn't have any right border.

**Comment by mauryaratan** [comment]
@lushkant I'll take over. Do we have related code in any branch or I need to start fresh?

**Comment by lushkant** [comment]
no I haven't pushed anything nor branch, you need to fresh start.

**Comment by lushkant** [comment]
(Duplicate issue) Refer to issue #34, to continue the conversation on the issue.
