### ISSUE TITLE
Missing support for Jetpack Social Menu

### ISSUE THREAD

**Issue by mauryaratan** [Codestag/thyself#14]
I see that support for `jetpack-social-menu` was added back in f7c24053842073edafe64a9fb4fd1cd7f1ad13d2 but it needs a front-end implementation as well.

**Comment by mauryaratan** [comment]
Right footer already has 2 blocks. I'd suggest keeping it on left 👍

**Comment by lushkant** [comment]
okay so should I do 
1. Left Menu Full Size Block and then Social Menu Full Size Block
2. Or Just Social Menu Full Size in place of current Left Menu Block

**Comment by mauryaratan** [comment]
Let's not replace the footer menu. And keep the social menu below it. And make sure the both left and right containers are horizontally aligned.

**Comment by lushkant** [comment]
Okay roger that! 👍
