### ISSUE TITLE
Homepage default layout

### ISSUE THREAD

**Issue by mauryaratan** [Codestag/thyself#18]
At present, the homepage is pretty messed up if full content is being displayed. I suggest showing excerpt by default.

And since its not a masonry layout, a long post can cause this to happen:

![image](https://user-images.githubusercontent.com/1505631/41285748-d585adf8-6e5a-11e8-84e1-17a9aec7ea86.png)

**Comment by lushkant** [comment]
You're right, we should go for excerpt on homepage and archives.
