### ISSUE TITLE
Is it wise to keep reading time on right side?

### ISSUE THREAD

**Issue by mauryaratan** [Codestag/thyself#23]
I suggest having reading time together along with other post meta, so its easier to scan details at once. We sure could use @JohnPixle's advice here 😕

**Comment by lushkant** [comment]
This is something we need to rethink, I'm not sure if it will be good on the left side 😕 .

**Comment by lushkant** [comment]
Hey Ram, I'm confirming again cause I'm a bit confused for the reading time alignment, should you agree on aligning it right or left?
