### ISSUE TITLE
Mobile Menu close button shouldn't scroll with content

### ISSUE THREAD

**Issue by mauryaratan** [Codestag/thyself#36]
When there is a large menu, the close button scrolls with the container. Make sure it sticks right there in top right corner.

![image](https://user-images.githubusercontent.com/1505631/41591588-ccda15a4-73d7-11e8-91a7-8889815e2232.png)

**Comment by lushkant** [comment]
@mauryaratan my firefox doesn't seem to have the same issue, on which device/platform/browser you tried?
![screenshot-2018-6-22 markup html tags and formatting thyself](https://user-images.githubusercontent.com/18240138/41771406-a95b2dfe-7632-11e8-9a6f-cc76c2b54619.png)
